name: validate
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: rinchsan/renovate-config-validator@v0.2.0
